### ISSUE TITLE
[Feature] : Homepage-related enhancements

### ISSUE THREAD

**Issue by 7jw92nVd1kLaq1** [Basket-Lounge/bl-backend#1]
## ✨ Feature description

Complete the following tasks for the completion of the home page

1. Fixing the API endpoint for retrieving the top 10 most popular posts
  - Load only the top 10 posts, posted within the same day
  - Load the link of the profile picture of a user that made a post
2. **(Optional)** Create an API endpoint for loading the information of the favorite team of a user
  - **Must be authenticated**
  - Here are a list of items that needs to be loaded
    - Team Logo
    - Team Name
    - Team Standing (W-L) (Ranking)

## ✅ Task(s)

- [x] Fix the API endpoint for retrieving the top 10 posts of the day
  - [x] Include the profile picture of a user of the post
- [ ] (Optional) Create the API endpoint for loading the information of the favorite team of a user
  - [ ] Include the followings: team logo, team name, team standing, team's wins and losses
