### ISSUE TITLE
[BUG] : Showing hidden posts to other users

### ISSUE THREAD

**Issue by 7jw92nVd1kLaq1** [Basket-Lounge/bl-backend#3]
## ✨ Bug description

Currently, the API endpoints retrieving a list of posts belonging to oneself and other users are not functioning as intended. Make sure to go over them to fully confirm that the posts not meant to be accessed other than authors themselves are not actually accessible by other users.

## ✅ Task(s) to resolve the bug

- [x] Go over each API endpoint and check their service logic
- [x] Introduce changes if necessary
- [x] Confirm the functionalities of API endpoints via testing
